import Head from "next/head";

import FrontPage from "../components/FrontPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Notion Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FrontPage />
    </div>
  );
}
